# Generated by Django 5.1.4 on 2025-02-10 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=100)),
                ('description', models.TextField(default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LossData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_name', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(choices=[('МСК КС Котельники', 'МСК КС Котельники'), ('МСК КС Саларьево', 'МСК КС Саларьево'), ('МСК КС Коммунальная', 'МСК КС Коммунальная'), ('МСК Мега Тёплый Стан', 'МСК Мега Тёплый Стан'), ('МСК Мега Химки', 'МСК Мега Химки'), ('МСК Мега Белая Дача', 'МСК Мега Белая Дача'), ('СПБ Мега Дыбенко', 'СПБ Мега Дыбенко'), ('СПБ Мега Паранс', 'СПБ Мега Паранс'), ('СПБ КС Шушары', 'СПБ КС Шушары')], default='МСК КС Котельники', max_length=50)),
                ('loss_type', models.CharField(choices=[('Склад', 'Склад'), ('Магистраль', 'Магистраль'), ('Сбор', 'Сбор'), ('Доставка', 'Доставка')], default='Склад', max_length=50)),
                ('count_loss', models.PositiveIntegerField(default=0)),
                ('cost_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_action_date', models.DateField(default=django.utils.timezone.now)),
                ('request_status', models.CharField(choices=[('Найден', 'Найден'), ('Запрос в СБ', 'Запрос в СБ'), ('Заключение', 'Заключение')], default='Найден', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('processed', models.IntegerField(default=0)),
                ('issued', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('system_stops', models.IntegerField(default=0)),
                ('awaiting', models.IntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('processed', models.IntegerField(default=0)),
                ('issued', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('system_stops', models.IntegerField(default=0)),
                ('expected', models.IntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
        ),
    ]
