# Generated by Django 5.1.4 on 2025-02-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseloss',
            name='cost_loss',
        ),
        migrations.RemoveField(
            model_name='warehouseloss',
            name='count_loss',
        ),
        migrations.AddField(
            model_name='warehouseloss',
            name='attachment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='warehouseloss',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='warehouseloss',
            name='culprit',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='warehouseloss',
            name='is_holding',
            field=models.CharField(choices=[('да', 'да'), ('нет', 'нет')], default='нет', max_length=3),
        ),
        migrations.AddField(
            model_name='warehouseloss',
            name='os',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouseloss',
            name='rp',
            field=models.CharField(default='RP', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='last_action_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='loss_type',
            field=models.CharField(choices=[('Склад', 'Склад'), ('Магистраль', 'Магистраль'), ('Сбор', 'Сбор'), ('Доставка', 'Доставка')], max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='request_status',
            field=models.CharField(choices=[('Найден', 'Найден'), ('Запрос в СБ', 'Запрос в СБ'), ('Заключение', 'Заключение')], max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='warehouse',
            field=models.CharField(choices=[('МСК КС Котельники', 'МСК КС Котельники'), ('МСК КС Саларьево', 'МСК КС Саларьево'), ('МСК КС Коммунальная', 'МСК КС Коммунальная'), ('МСК Мега Тёплый Стан', 'МСК Мега Тёплый Стан'), ('МСК Мега Химки', 'МСК Мега Химки'), ('МСК Мега Белая Дача', 'МСК Мега Белая Дача'), ('СПБ Мега Дыбенко', 'СПБ Мега Дыбенко'), ('СПБ Мега Паранс', 'СПБ Мега Паранс'), ('СПБ КС Шушары', 'СПБ КС Шушары')], max_length=255),
        ),
    ]
