# Generated by Django 5.1.4 on 2025-02-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_warehouseloss_cost_loss_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseloss',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='culprit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
