# Generated by Django 5.1.4 on 2025-02-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehouseloss_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseloss',
            name='retained',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='no', max_length=3, verbose_name='Удержано'),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='culprit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='is_holding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='rp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehouseloss',
            name='warehouse',
            field=models.CharField(choices=[('МСК КС Котельники', 'МСК КС Котельники'), ('МСК КС Саларьево', 'МСК КС Саларьево'), ('МСК КС Коммунальная', 'МСК КС Коммунальная'), ('МСК Мега Тёплый Стан', 'МСК Мега Тёплый Стан'), ('МСК Мега Химки', 'МСК Мега Химки'), ('МСК Мега Белая Дача', 'МСК Мега Белая Дача'), ('СПБ Мега Дыбенко', 'СПБ Мега Дыбенко'), ('СПБ Мега Паранс', 'СПБ Мега Паранс'), ('СПБ КС Шушары', 'СПБ КС Шушары')], max_length=50),
        ),
    ]
