# Generated by Django 5.1.4 on 2025-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_warehouseloss_retained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseloss',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
