# Generated by Django 5.1.4 on 2025-02-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_warehouseloss_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseloss',
            name='attachment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
