# Generated by Django 5.1.4 on 2025-02-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_warehouseloss_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseloss',
            name='attachment',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
